# TB_ROOM: 기본 정보와 대부분의 컬럼을 포함한 테이블.
CREATE TABLE TB_ROOM
(
    ROOM_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    VIDEO_TYPE    INT DEFAULT 0 NOT NULL,
    ROOM_TYPE     VARCHAR(20) DEFAULT 'room' NOT NULL,
    IS_CHANNEL    TINYINT DEFAULT 0 NOT NULL,
    DESCRIPTION   VARCHAR(200) NOT NULL,
    PASSCODE      VARCHAR(10),
    THUMBNAIL     VARCHAR(200) DEFAULT '' NOT NULL,
    JSON_LINK     VARCHAR(200),
    PRIVATE       TINYINT DEFAULT 0 NOT NULL COMMENT '1 is public 0 is private room with passcode',
    LAT           VARCHAR(20) DEFAULT '' NOT NULL,
    LON           VARCHAR(20) DEFAULT '' NOT NULL,
    CATEGORY      VARCHAR(50) DEFAULT '' NOT NULL,
    USER_MAX      INT DEFAULT 10 NOT NULL,
    CHANNELS      VARCHAR(2000) DEFAULT '[]' NOT NULL,
    TITLE         VARCHAR(200) NOT NULL,
    BIG_THUMBNAIL VARCHAR(200) NOT NULL,
    GIS_NO        VARCHAR(50) NOT NULL,
    ROOM_LV       INT DEFAULT 1 NOT NULL,
    DELETED       TINYINT DEFAULT 0 NOT NULL,
    UPDATE_AT     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NULL ON UPDATE CURRENT_TIMESTAMP(6),
    CREATE_AT     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL
);

# TB_ROOM_USER: 각 방(Room)에 대한 사용자 정보를 저장하는 테이블.
CREATE TABLE TB_ROOM_USER
(
    ROOM_USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROOM_ID      BIGINT NOT NULL,
    USERS        INT DEFAULT 0 NOT NULL,
    FOREIGN KEY (ROOM_ID) REFERENCES TB_ROOM (ROOM_ID)
);

# TB_ROOM_ASSET: 각 방(Room)에 대한 자산 정보를 저장하는 테이블.
CREATE TABLE TB_ROOM_ASSET
(
    ROOM_ASSET_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROOM_ID       BIGINT NOT NULL,
    ASSET_ID_IOS  INT DEFAULT 0 NOT NULL,
    ASSET_ID_AOS  INT DEFAULT 0 NOT NULL,
    FOREIGN KEY (ROOM_ID) REFERENCES TB_ROOM (ROOM_ID)
);

# TB_ROOM_FILE: 각 방(Room)에 대한 파일 링크 정보를 저장하는 테이블.
CREATE TABLE TB_ROOM_FILE
(
    ROOM_FILE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROOM_ID      BIGINT NOT NULL,
    FILE_LINK    VARCHAR(200),
    FOREIGN KEY (ROOM_ID) REFERENCES TB_ROOM (ROOM_ID)
);
